//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationArcMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationArcMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize API failed.
        /// </summary>
        internal static string FrmGlobespotter_OnAPIFailed_Initialize_API_failed {
            get {
                return ResourceManager.GetString("FrmGlobespotter_OnAPIFailed_Initialize_API_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globespotter integration Addin Error..
        /// </summary>
        internal static string GsCycloMediaOptions_OnClick_Globespotter_integration_Addin_Error_ {
            get {
                return ResourceManager.GetString("GsCycloMediaOptions_OnClick_Globespotter_integration_Addin_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GsDelete {
            get {
                object obj = ResourceManager.GetObject("GsDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adobe reader is not installed.
        /// </summary>
        internal static string GsHelp_OnClick_adobe_reader_is_not_installed {
            get {
                return ResourceManager.GetString("GsHelp_OnClick_adobe_reader_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe reader is not installed on your system, please first install adobe reader.
        /// </summary>
        internal static string GsHelp_OnClick_Adobe_reader_is_not_installed_on_your_system__please_first_install_adobe_reader {
            get {
                return ResourceManager.GetString("GsHelp_OnClick_Adobe_reader_is_not_installed_on_your_system__please_first_install" +
                        "_adobe_reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view the image..
        /// </summary>
        internal static string GsOpenLocation_OnMouseUp_You_are_not_authorized_to_view_the_image_ {
            get {
                return ResourceManager.GetString("GsOpenLocation_OnMouseUp_You_are_not_authorized_to_view_the_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        internal static string Login_CreateAes_Password_must_be_at_least_8_characters_ {
            get {
                return ResourceManager.GetString("Login_CreateAes_Password_must_be_at_least_8_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt must be at least 8 bytes..
        /// </summary>
        internal static string Login_CreateAes_Salt_must_be_at_least_8_bytes_ {
            get {
                return ResourceManager.GetString("Login_CreateAes_Salt_must_be_at_least_8_bytes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
